trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  name: $(imageName)
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: 'python -m pip install .'
  displayName: 'Run Pip Install'

- script: 'python -m pytest -v tests.py  --junitxml=test_results.xml'
  workingDirectory: pycopier/tests
  displayName: 'Run Pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test_results*.xml'
  inputs:
    testResultsFiles: '**/test_results*.xml'


