trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
- job: macOS
  pool:
    vmImage: 'macOS-latest'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: 'python -m pip install .'
  displayName: 'Run Pip Install'

- script: 'python -m pytest -v tests.py  --junitxml=test_results.xml'
  workingDirectory: pycopier/tests
  displayName: 'Run Pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test_results*.xml'
  inputs:
    testResultsFiles: '**/test_results*.xml'


